apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crypto-app.fullname" . }}-secret
  labels:
    {{- include "crypto-app.labels" . | nindent 4 }}
data:
  rootPassword: cGFzc3dvcmQ=
  database: bW92aW1pZW50b3M=
  password: cGFzc3dvcmQ=
  username: a2NfdXNlcg==
  
  